name: 🐞 Bug
description: Déclarer un bug ou un comportement inattendu
title: "client : sujet"
labels:
  - bug
projects:
  - d4e-digital-4-efficiency/5
assignees: []

body:
  - type: textarea
    id: contexte
    attributes:
      label: 📝 Contexte / besoin métier / fonctionnel
      description: Décrire le contexte, l’objectif métier ou fonctionnel, et pourquoi c’est nécessaire.
      placeholder: Expliquer la situation, les enjeux et le but recherché...
    validations:
      required: true

  - type: textarea
    id: comportement-actuel
    attributes:
      label: 🔍 Comportement actuel
      description: Décrire le comportement observé actuellement et indiquer si c’est reproductible.
      placeholder: Décrire précisément le problème...
    validations:
      required: true

  - type: textarea
    id: comportement-attendu
    attributes:
      label: ✅ Comportement attendu
      description: Décrire clairement le comportement attendu si le bug n’existait pas.
      placeholder: Décrire ce qui devrait se passer...
    validations:
      required: true

  - type: textarea
    id: plan-de-test
    attributes:
      label: 🧪 Plan de test
      description: Lister les scénarios OK et KO.
      value: |
        ### Cas OK
        - 

        ### Cas KO
        - 
    validations:
      required: false

