name: ✨ Nouvelle fonctionnalité
description: Décrire une évolution ou un besoin métier
title: "client : sujet"
labels: []
projects:
  - d4e-digital-4-efficiency/5
assignees: []
type: Feature

body:
  - type: markdown
    attributes:
      value: |
        > ℹ️ **Indication pour les chefs de projet**
        > Merci d’**ajouter des tags/labels** sur l’issue :
        > - **Durée estimée**
        > - **Module(s) concerné(s)**
        >
        > Ne pas hésiter à mettre une **vidéo** et/ou des captures d'écran pour illustrer le problème.
        >
        > Si des compléments sont nécessaires, merci de les ajouter dans la description initiale de la tâche en plus d'un commentaire.


  - type: textarea
    id: contexte
    attributes:
      label: 📝 Contexte / besoin métier / fonctionnel
      description: Décrire le contexte, l’objectif métier ou fonctionnel, et pourquoi c’est nécessaire.
      placeholder: Expliquer la situation, les enjeux et le but recherché...
    validations:
      required: true

  - type: textarea
    id: comportement-attendu
    attributes:
      label: ✅ Comportement attendu
      description: Décrire clairement le comportement souhaité.
      placeholder: Décrire ce qui devrait se passer...
      value: |
        - 
        
                
        Indication pour les **développeurs**
        Ne pas hésiter à **revenir vers le demandeur** si l'estimation de temps est insuffisante, si le module indiqué n'est pas le bon, si besoin d'un **appel pour clarifier** le besoin, ...
    validations:
      required: true

  
  - type: textarea
    id: plan-de-test
    attributes:
      label: 🧪 Plan de test
      description: Lister les scénarios de validation et d’échec.
      value: |
        ### Cas OK
        -

        ### Cas KO
        -
    validations:
      required: false

  - type: textarea
    id: documentation
    attributes:
      label: 📝 Documentation
      description: Gérer la documentation dans le fichier README.md du module concerné.
      value: |
        - [ ] README.md du module créé ou mis à jour
        - [ ] Noms des variables et fonctions clairs
        - [ ] Commentaires dans le code si nécessaire
        - [ ] TODO dans le code ou dans le README.md si nécessaire (bugs identifiés, améliorations possibles, ...)