name: ✨ Nouvelle fonctionnalité
description: Décrire une évolution ou un besoin métier
title: "client : sujet"
labels: []
projects:
  - d4e-digital-4-efficiency/5
assignees: []

body:
  - type: textarea
    id: contexte
    attributes:
      label: 📝 Contexte / besoin métier / fonctionnel
      description: Décrire le contexte, l’objectif métier ou fonctionnel, et pourquoi c’est nécessaire.
      placeholder: Expliquer la situation, les enjeux et le but recherché...
    validations:
      required: true

  - type: textarea
    id: comportement-attendu
    attributes:
      label: ✅ Comportement attendu
      description: Décrire clairement le comportement souhaité.
      placeholder: Décrire ce qui devrait se passer...
    validations:
      required: true

  - type: textarea
    id: plan-de-test
    attributes:
      label: 🧪 Plan de test
      description: Lister les scénarios de validation et d’échec.
      value: |
        ### Cas OK
        - 

        ### Cas KO
        - 
    validations:
      required: false

