name: 🛠️ Tâche technique
description: Décrire une tâche technique, de maintenance ou d'amélioration interne
title: "client : sujet"
labels: []
projects:
  - d4e-digital-4-efficiency/5
assignees: []
type: Task

body:
  - type: markdown
    attributes:
      value: |
        > ℹ️ **Indication**
        > Merci d’**ajouter des tags/labels** sur l’issue :
        > - **Durée estimée**
        > - **Module(s) concerné(s)**
        >
        > Si des compléments sont nécessaires, merci de les ajouter dans la description initiale de la tâche en plus d'un commentaire.

  - type: textarea
    id: contexte
    attributes:
      label: 📝 Contexte / objectif technique
      description: Décrire le contexte technique, l'objectif et pourquoi cette tâche est nécessaire.
      placeholder: Expliquer la situation, le problème technique ou l'optimisation recherchée...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📋 Détails de la tâche
      description: Décrire précisément ce qu'il faut faire (étapes, composants, contraintes).
      placeholder: Liste des étapes ou description technique...
    validations:
      required: true

  - type: textarea
    id: plan-de-test
    attributes:
      label: 🧪 Plan de test
      description: Lister les scénarios de validation et d’échec (si applicable).
      value: |
        ### Cas OK
        -

        ### Cas KO
        - 
    validations:
      required: false
